envs:
  local-dev:
    PIPELINE_NAME: "stock_train_pipeline"
    PROJECT_ID: "crafty-student-446923-n5"
    SERVICE_ACCOUNT: "ailabs-mlops@crafty-student-446923-n5.iam.gserviceaccount.com"
    LOCATION: "us-central1"
    SA_PATH: "/Users/j0c0p72/Downloads/crafty-student-446923-n5-3ac6a1c11c45.json"
    # Custom/User-Defined
    RECIPIENTS_LIST: ["jae.hyuk.choi.0325@gmail.com"]
    FEATURE_METADATA: {
      training_table_name: "crafty-student-446923-n5.stock.raw_nse_tataglobal",
      time_col: "Date",
      is_log: True,
    }
    MODEL_REGISTRY_METADATA: {
      "model_registry_table_name": "crafty-student-446923-n5.model_registry.model_metrics",
      "model_registry_bucket_name": "ailabs-mlops-model-registry",
      "model_versions": {
        "ma": "v1",
        "arima": "v1",
        "lstm": "v1",
      },
      "model_types": {
        "ma": "None",
        "arima": "joblib",
        "lstm": "keras",
      }
    }
    SAVE_PRED_TABLE_NAME: "crafty-student-446923-n5.stock.predict"
  dev:
    PROJECT_ID: "crafty-student-446923-n5"
  stage:
    PROJECT_ID: "crafty-student-446923-n5"
  prod:
    PROJECT_ID: "crafty-student-446923-n5"